version: '3.8'
services:
  ecommerce-api:
    image: ecommerce
    container_name: ecommerce
    hostname: ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgres
    volumes:
      - ./logs:/logs
  dbpostgres:
    image: postgres:10.7
    container_name: dbpostgres
    hostname: dbpostgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
          - 5442:5442
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres